// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/rewriter_config.proto

package org.tensorflow.framework;

public final class RewriterConfigProtos {
  private RewriterConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AutoParallelOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AutoParallelOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RewriterConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RewriterConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.tensorflow/core/protobuf/rewriter_conf" +
      "ig.proto\022\ntensorflow\";\n\023AutoParallelOpti" +
      "ons\022\016\n\006enable\030\001 \001(\010\022\024\n\014num_replicas\030\002 \001(" +
      "\005\"\243\002\n\016RewriterConfig\022\036\n\026optimize_tensor_" +
      "layout\030\001 \001(\010\022\035\n\025disable_model_pruning\030\002 " +
      "\001(\010\022\030\n\020constant_folding\030\003 \001(\010\022B\n\023memory_" +
      "optimization\030\004 \001(\0162%.tensorflow.Rewriter" +
      "Config.MemOptType\0226\n\rauto_parallel\030\005 \001(\013" +
      "2\037.tensorflow.AutoParallelOptions\022\022\n\nopt" +
      "imizers\030d \003(\t\"(\n\nMemOptType\022\016\n\nNO_MEM_OP",
      "T\020\000\022\n\n\006MANUAL\020\001B5\n\030org.tensorflow.framew" +
      "orkB\024RewriterConfigProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_AutoParallelOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_AutoParallelOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AutoParallelOptions_descriptor,
        new java.lang.String[] { "Enable", "NumReplicas", });
    internal_static_tensorflow_RewriterConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_RewriterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RewriterConfig_descriptor,
        new java.lang.String[] { "OptimizeTensorLayout", "DisableModelPruning", "ConstantFolding", "MemoryOptimization", "AutoParallel", "Optimizers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
