// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master.proto

package org.tensorflow.distruntime;

public interface ListDevicesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ListDevicesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional: session_handle must be returned by a CreateSession call to the
   * same master service.
   * When session_handle is empty, the ClusterSpec provided when the master was
   * started is used to compute the available devices. If the session_handle is
   * provided but not recognized, an error is returned. Finally, if a valid
   * session_handle is provided, the cluster configuration for that session is
   * used when computing the response.
   * </pre>
   *
   * <code>string session_handle = 1;</code>
   */
  java.lang.String getSessionHandle();
  /**
   * <pre>
   * Optional: session_handle must be returned by a CreateSession call to the
   * same master service.
   * When session_handle is empty, the ClusterSpec provided when the master was
   * started is used to compute the available devices. If the session_handle is
   * provided but not recognized, an error is returned. Finally, if a valid
   * session_handle is provided, the cluster configuration for that session is
   * used when computing the response.
   * </pre>
   *
   * <code>string session_handle = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionHandleBytes();
}
