// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master.proto

package org.tensorflow.distruntime;

public interface MakeCallableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MakeCallableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A handle to the created callable.
   * </pre>
   *
   * <code>int64 handle = 1;</code>
   */
  long getHandle();
}
