// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/kernels/boosted_trees/boosted_trees.proto

package org.tensorflow.framework;

public final class BoostedTreesProtos {
  private BoostedTreesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_NodeMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_NodeMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_Leaf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_Leaf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_Vector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_SparseVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_SparseVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_BucketizedSplit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_Tree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_Tree_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_TreeMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_TreeMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_TreeMetadata_PostPruneNodeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_TreeMetadata_PostPruneNodeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_GrowingMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_GrowingMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_boosted_trees_TreeEnsemble_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_boosted_trees_TreeEnsemble_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9tensorflow/core/kernels/boosted_trees/" +
      "boosted_trees.proto\022\030tensorflow.boosted_" +
      "trees\"\300\001\n\004Node\022.\n\004leaf\030\001 \001(\0132\036.tensorflo" +
      "w.boosted_trees.LeafH\000\022E\n\020bucketized_spl" +
      "it\030\002 \001(\0132).tensorflow.boosted_trees.Buck" +
      "etizedSplitH\000\0229\n\010metadata\030\211\006 \001(\0132&.tenso" +
      "rflow.boosted_trees.NodeMetadataB\006\n\004node" +
      "\"S\n\014NodeMetadata\022\014\n\004gain\030\001 \001(\002\0225\n\rorigin" +
      "al_leaf\030\002 \001(\0132\036.tensorflow.boosted_trees" +
      ".Leaf\"\223\001\n\004Leaf\0222\n\006vector\030\001 \001(\0132 .tensorf",
      "low.boosted_trees.VectorH\000\022?\n\rsparse_vec" +
      "tor\030\002 \001(\0132&.tensorflow.boosted_trees.Spa" +
      "rseVectorH\000\022\016\n\006scalar\030\003 \001(\002B\006\n\004leaf\"\027\n\006V" +
      "ector\022\r\n\005value\030\001 \003(\002\",\n\014SparseVector\022\r\n\005" +
      "index\030\001 \003(\005\022\r\n\005value\030\002 \003(\002\"[\n\017Bucketized" +
      "Split\022\022\n\nfeature_id\030\001 \001(\005\022\021\n\tthreshold\030\002" +
      " \001(\005\022\017\n\007left_id\030\003 \001(\005\022\020\n\010right_id\030\004 \001(\005\"" +
      "5\n\004Tree\022-\n\005nodes\030\001 \003(\0132\036.tensorflow.boos" +
      "ted_trees.Node\"\334\001\n\014TreeMetadata\022\030\n\020num_l" +
      "ayers_grown\030\002 \001(\005\022\024\n\014is_finalized\030\003 \001(\010\022",
      "Z\n\026post_pruned_nodes_meta\030\004 \003(\0132:.tensor" +
      "flow.boosted_trees.TreeMetadata.PostPrun" +
      "eNodeUpdate\032@\n\023PostPruneNodeUpdate\022\023\n\013ne" +
      "w_node_id\030\001 \001(\005\022\024\n\014logit_change\030\002 \001(\002\"L\n" +
      "\017GrowingMetadata\022\033\n\023num_trees_attempted\030" +
      "\001 \001(\003\022\034\n\024num_layers_attempted\030\002 \001(\003\"\327\001\n\014" +
      "TreeEnsemble\022-\n\005trees\030\001 \003(\0132\036.tensorflow" +
      ".boosted_trees.Tree\022\024\n\014tree_weights\030\002 \003(" +
      "\002\022=\n\rtree_metadata\030\003 \003(\0132&.tensorflow.bo" +
      "osted_trees.TreeMetadata\022C\n\020growing_meta",
      "data\030\004 \001(\0132).tensorflow.boosted_trees.Gr" +
      "owingMetadataB3\n\030org.tensorflow.framewor" +
      "kB\022BoostedTreesProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_boosted_trees_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_boosted_trees_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_Node_descriptor,
        new java.lang.String[] { "Leaf", "BucketizedSplit", "Metadata", "Node", });
    internal_static_tensorflow_boosted_trees_NodeMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_boosted_trees_NodeMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_NodeMetadata_descriptor,
        new java.lang.String[] { "Gain", "OriginalLeaf", });
    internal_static_tensorflow_boosted_trees_Leaf_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_boosted_trees_Leaf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_Leaf_descriptor,
        new java.lang.String[] { "Vector", "SparseVector", "Scalar", "Leaf", });
    internal_static_tensorflow_boosted_trees_Vector_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_boosted_trees_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_Vector_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_boosted_trees_SparseVector_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_boosted_trees_SparseVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_SparseVector_descriptor,
        new java.lang.String[] { "Index", "Value", });
    internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_boosted_trees_BucketizedSplit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor,
        new java.lang.String[] { "FeatureId", "Threshold", "LeftId", "RightId", });
    internal_static_tensorflow_boosted_trees_Tree_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_boosted_trees_Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_Tree_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_tensorflow_boosted_trees_TreeMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tensorflow_boosted_trees_TreeMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_TreeMetadata_descriptor,
        new java.lang.String[] { "NumLayersGrown", "IsFinalized", "PostPrunedNodesMeta", });
    internal_static_tensorflow_boosted_trees_TreeMetadata_PostPruneNodeUpdate_descriptor =
      internal_static_tensorflow_boosted_trees_TreeMetadata_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_boosted_trees_TreeMetadata_PostPruneNodeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_TreeMetadata_PostPruneNodeUpdate_descriptor,
        new java.lang.String[] { "NewNodeId", "LogitChange", });
    internal_static_tensorflow_boosted_trees_GrowingMetadata_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tensorflow_boosted_trees_GrowingMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_GrowingMetadata_descriptor,
        new java.lang.String[] { "NumTreesAttempted", "NumLayersAttempted", });
    internal_static_tensorflow_boosted_trees_TreeEnsemble_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tensorflow_boosted_trees_TreeEnsemble_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_boosted_trees_TreeEnsemble_descriptor,
        new java.lang.String[] { "Trees", "TreeWeights", "TreeMetadata", "GrowingMetadata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
