// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/kernels/boosted_trees/boosted_trees.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.boosted_trees.BucketizedSplit}
 */
public  final class BucketizedSplit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.boosted_trees.BucketizedSplit)
    BucketizedSplitOrBuilder {
  // Use BucketizedSplit.newBuilder() to construct.
  private BucketizedSplit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BucketizedSplit() {
    featureId_ = 0;
    threshold_ = 0;
    leftId_ = 0;
    rightId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BucketizedSplit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            featureId_ = input.readInt32();
            break;
          }
          case 16: {

            threshold_ = input.readInt32();
            break;
          }
          case 24: {

            leftId_ = input.readInt32();
            break;
          }
          case 32: {

            rightId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.BoostedTreesProtos.internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.BoostedTreesProtos.internal_static_tensorflow_boosted_trees_BucketizedSplit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.BucketizedSplit.class, org.tensorflow.framework.BucketizedSplit.Builder.class);
  }

  public static final int FEATURE_ID_FIELD_NUMBER = 1;
  private int featureId_;
  /**
   * <pre>
   * Float feature column and split threshold describing
   * the rule feature &lt;= threshold.
   * </pre>
   *
   * <code>int32 feature_id = 1;</code>
   */
  public int getFeatureId() {
    return featureId_;
  }

  public static final int THRESHOLD_FIELD_NUMBER = 2;
  private int threshold_;
  /**
   * <code>int32 threshold = 2;</code>
   */
  public int getThreshold() {
    return threshold_;
  }

  public static final int LEFT_ID_FIELD_NUMBER = 3;
  private int leftId_;
  /**
   * <pre>
   * Node children indexing into a contiguous
   * vector of nodes starting from the root.
   * </pre>
   *
   * <code>int32 left_id = 3;</code>
   */
  public int getLeftId() {
    return leftId_;
  }

  public static final int RIGHT_ID_FIELD_NUMBER = 4;
  private int rightId_;
  /**
   * <code>int32 right_id = 4;</code>
   */
  public int getRightId() {
    return rightId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (featureId_ != 0) {
      output.writeInt32(1, featureId_);
    }
    if (threshold_ != 0) {
      output.writeInt32(2, threshold_);
    }
    if (leftId_ != 0) {
      output.writeInt32(3, leftId_);
    }
    if (rightId_ != 0) {
      output.writeInt32(4, rightId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (featureId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, featureId_);
    }
    if (threshold_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, threshold_);
    }
    if (leftId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, leftId_);
    }
    if (rightId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, rightId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.framework.BucketizedSplit)) {
      return super.equals(obj);
    }
    org.tensorflow.framework.BucketizedSplit other = (org.tensorflow.framework.BucketizedSplit) obj;

    boolean result = true;
    result = result && (getFeatureId()
        == other.getFeatureId());
    result = result && (getThreshold()
        == other.getThreshold());
    result = result && (getLeftId()
        == other.getLeftId());
    result = result && (getRightId()
        == other.getRightId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FEATURE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFeatureId();
    hash = (37 * hash) + THRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + getThreshold();
    hash = (37 * hash) + LEFT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeftId();
    hash = (37 * hash) + RIGHT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRightId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.framework.BucketizedSplit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.BucketizedSplit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.BucketizedSplit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.BucketizedSplit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.boosted_trees.BucketizedSplit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.boosted_trees.BucketizedSplit)
      org.tensorflow.framework.BucketizedSplitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.BoostedTreesProtos.internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.BoostedTreesProtos.internal_static_tensorflow_boosted_trees_BucketizedSplit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.BucketizedSplit.class, org.tensorflow.framework.BucketizedSplit.Builder.class);
    }

    // Construct using org.tensorflow.framework.BucketizedSplit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      featureId_ = 0;

      threshold_ = 0;

      leftId_ = 0;

      rightId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.BoostedTreesProtos.internal_static_tensorflow_boosted_trees_BucketizedSplit_descriptor;
    }

    public org.tensorflow.framework.BucketizedSplit getDefaultInstanceForType() {
      return org.tensorflow.framework.BucketizedSplit.getDefaultInstance();
    }

    public org.tensorflow.framework.BucketizedSplit build() {
      org.tensorflow.framework.BucketizedSplit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.BucketizedSplit buildPartial() {
      org.tensorflow.framework.BucketizedSplit result = new org.tensorflow.framework.BucketizedSplit(this);
      result.featureId_ = featureId_;
      result.threshold_ = threshold_;
      result.leftId_ = leftId_;
      result.rightId_ = rightId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.BucketizedSplit) {
        return mergeFrom((org.tensorflow.framework.BucketizedSplit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.BucketizedSplit other) {
      if (other == org.tensorflow.framework.BucketizedSplit.getDefaultInstance()) return this;
      if (other.getFeatureId() != 0) {
        setFeatureId(other.getFeatureId());
      }
      if (other.getThreshold() != 0) {
        setThreshold(other.getThreshold());
      }
      if (other.getLeftId() != 0) {
        setLeftId(other.getLeftId());
      }
      if (other.getRightId() != 0) {
        setRightId(other.getRightId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.BucketizedSplit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.BucketizedSplit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int featureId_ ;
    /**
     * <pre>
     * Float feature column and split threshold describing
     * the rule feature &lt;= threshold.
     * </pre>
     *
     * <code>int32 feature_id = 1;</code>
     */
    public int getFeatureId() {
      return featureId_;
    }
    /**
     * <pre>
     * Float feature column and split threshold describing
     * the rule feature &lt;= threshold.
     * </pre>
     *
     * <code>int32 feature_id = 1;</code>
     */
    public Builder setFeatureId(int value) {
      
      featureId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Float feature column and split threshold describing
     * the rule feature &lt;= threshold.
     * </pre>
     *
     * <code>int32 feature_id = 1;</code>
     */
    public Builder clearFeatureId() {
      
      featureId_ = 0;
      onChanged();
      return this;
    }

    private int threshold_ ;
    /**
     * <code>int32 threshold = 2;</code>
     */
    public int getThreshold() {
      return threshold_;
    }
    /**
     * <code>int32 threshold = 2;</code>
     */
    public Builder setThreshold(int value) {
      
      threshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 threshold = 2;</code>
     */
    public Builder clearThreshold() {
      
      threshold_ = 0;
      onChanged();
      return this;
    }

    private int leftId_ ;
    /**
     * <pre>
     * Node children indexing into a contiguous
     * vector of nodes starting from the root.
     * </pre>
     *
     * <code>int32 left_id = 3;</code>
     */
    public int getLeftId() {
      return leftId_;
    }
    /**
     * <pre>
     * Node children indexing into a contiguous
     * vector of nodes starting from the root.
     * </pre>
     *
     * <code>int32 left_id = 3;</code>
     */
    public Builder setLeftId(int value) {
      
      leftId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Node children indexing into a contiguous
     * vector of nodes starting from the root.
     * </pre>
     *
     * <code>int32 left_id = 3;</code>
     */
    public Builder clearLeftId() {
      
      leftId_ = 0;
      onChanged();
      return this;
    }

    private int rightId_ ;
    /**
     * <code>int32 right_id = 4;</code>
     */
    public int getRightId() {
      return rightId_;
    }
    /**
     * <code>int32 right_id = 4;</code>
     */
    public Builder setRightId(int value) {
      
      rightId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 right_id = 4;</code>
     */
    public Builder clearRightId() {
      
      rightId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.boosted_trees.BucketizedSplit)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.boosted_trees.BucketizedSplit)
  private static final org.tensorflow.framework.BucketizedSplit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.BucketizedSplit();
  }

  public static org.tensorflow.framework.BucketizedSplit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BucketizedSplit>
      PARSER = new com.google.protobuf.AbstractParser<BucketizedSplit>() {
    public BucketizedSplit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BucketizedSplit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BucketizedSplit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BucketizedSplit> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.BucketizedSplit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

