// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/critical_section.proto

package org.tensorflow.framework;

/**
 * <pre>
 * Protocol buffer representing a CriticalSection.
 * </pre>
 *
 * Protobuf type {@code tensorflow.CriticalSectionDef}
 */
public  final class CriticalSectionDef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.CriticalSectionDef)
    CriticalSectionDefOrBuilder {
  // Use CriticalSectionDef.newBuilder() to construct.
  private CriticalSectionDef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CriticalSectionDef() {
    criticalSectionName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CriticalSectionDef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            criticalSectionName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.CriticalSectionProtos.internal_static_tensorflow_CriticalSectionDef_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.CriticalSectionProtos.internal_static_tensorflow_CriticalSectionDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.CriticalSectionDef.class, org.tensorflow.framework.CriticalSectionDef.Builder.class);
  }

  public static final int CRITICAL_SECTION_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object criticalSectionName_;
  /**
   * <pre>
   * Name of the critical section handle.
   * </pre>
   *
   * <code>string critical_section_name = 1;</code>
   */
  public java.lang.String getCriticalSectionName() {
    java.lang.Object ref = criticalSectionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      criticalSectionName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the critical section handle.
   * </pre>
   *
   * <code>string critical_section_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCriticalSectionNameBytes() {
    java.lang.Object ref = criticalSectionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      criticalSectionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCriticalSectionNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, criticalSectionName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCriticalSectionNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, criticalSectionName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.framework.CriticalSectionDef)) {
      return super.equals(obj);
    }
    org.tensorflow.framework.CriticalSectionDef other = (org.tensorflow.framework.CriticalSectionDef) obj;

    boolean result = true;
    result = result && getCriticalSectionName()
        .equals(other.getCriticalSectionName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CRITICAL_SECTION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCriticalSectionName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.framework.CriticalSectionDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.CriticalSectionDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Protocol buffer representing a CriticalSection.
   * </pre>
   *
   * Protobuf type {@code tensorflow.CriticalSectionDef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.CriticalSectionDef)
      org.tensorflow.framework.CriticalSectionDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.CriticalSectionProtos.internal_static_tensorflow_CriticalSectionDef_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.CriticalSectionProtos.internal_static_tensorflow_CriticalSectionDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.CriticalSectionDef.class, org.tensorflow.framework.CriticalSectionDef.Builder.class);
    }

    // Construct using org.tensorflow.framework.CriticalSectionDef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      criticalSectionName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.CriticalSectionProtos.internal_static_tensorflow_CriticalSectionDef_descriptor;
    }

    public org.tensorflow.framework.CriticalSectionDef getDefaultInstanceForType() {
      return org.tensorflow.framework.CriticalSectionDef.getDefaultInstance();
    }

    public org.tensorflow.framework.CriticalSectionDef build() {
      org.tensorflow.framework.CriticalSectionDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.CriticalSectionDef buildPartial() {
      org.tensorflow.framework.CriticalSectionDef result = new org.tensorflow.framework.CriticalSectionDef(this);
      result.criticalSectionName_ = criticalSectionName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.CriticalSectionDef) {
        return mergeFrom((org.tensorflow.framework.CriticalSectionDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.CriticalSectionDef other) {
      if (other == org.tensorflow.framework.CriticalSectionDef.getDefaultInstance()) return this;
      if (!other.getCriticalSectionName().isEmpty()) {
        criticalSectionName_ = other.criticalSectionName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.CriticalSectionDef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.CriticalSectionDef) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object criticalSectionName_ = "";
    /**
     * <pre>
     * Name of the critical section handle.
     * </pre>
     *
     * <code>string critical_section_name = 1;</code>
     */
    public java.lang.String getCriticalSectionName() {
      java.lang.Object ref = criticalSectionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        criticalSectionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the critical section handle.
     * </pre>
     *
     * <code>string critical_section_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCriticalSectionNameBytes() {
      java.lang.Object ref = criticalSectionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        criticalSectionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the critical section handle.
     * </pre>
     *
     * <code>string critical_section_name = 1;</code>
     */
    public Builder setCriticalSectionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      criticalSectionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the critical section handle.
     * </pre>
     *
     * <code>string critical_section_name = 1;</code>
     */
    public Builder clearCriticalSectionName() {
      
      criticalSectionName_ = getDefaultInstance().getCriticalSectionName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the critical section handle.
     * </pre>
     *
     * <code>string critical_section_name = 1;</code>
     */
    public Builder setCriticalSectionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      criticalSectionName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.CriticalSectionDef)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.CriticalSectionDef)
  private static final org.tensorflow.framework.CriticalSectionDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.CriticalSectionDef();
  }

  public static org.tensorflow.framework.CriticalSectionDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CriticalSectionDef>
      PARSER = new com.google.protobuf.AbstractParser<CriticalSectionDef>() {
    public CriticalSectionDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CriticalSectionDef(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CriticalSectionDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CriticalSectionDef> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.CriticalSectionDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

