// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/kernels/boosted_trees/boosted_trees.proto

package org.tensorflow.framework;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.boosted_trees.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.boosted_trees.Leaf leaf = 1;</code>
   */
  org.tensorflow.framework.Leaf getLeaf();
  /**
   * <code>.tensorflow.boosted_trees.Leaf leaf = 1;</code>
   */
  org.tensorflow.framework.LeafOrBuilder getLeafOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.BucketizedSplit bucketized_split = 2;</code>
   */
  org.tensorflow.framework.BucketizedSplit getBucketizedSplit();
  /**
   * <code>.tensorflow.boosted_trees.BucketizedSplit bucketized_split = 2;</code>
   */
  org.tensorflow.framework.BucketizedSplitOrBuilder getBucketizedSplitOrBuilder();

  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  boolean hasMetadata();
  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  org.tensorflow.framework.NodeMetadata getMetadata();
  /**
   * <code>.tensorflow.boosted_trees.NodeMetadata metadata = 777;</code>
   */
  org.tensorflow.framework.NodeMetadataOrBuilder getMetadataOrBuilder();

  public org.tensorflow.framework.Node.NodeCase getNodeCase();
}
