// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/verbs/verbs_service.proto

package org.tensorflow.contrib.verbs;

public interface ChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Channel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lid = 1;</code>
   */
  int getLid();

  /**
   * <code>int32 qpn = 2;</code>
   */
  int getQpn();

  /**
   * <code>int32 psn = 3;</code>
   */
  int getPsn();

  /**
   * <code>uint64 snp = 4;</code>
   */
  long getSnp();

  /**
   * <code>uint64 iid = 5;</code>
   */
  long getIid();
}
