// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/verbs/verbs_service.proto

package org.tensorflow.contrib.verbs;

public interface GetRemoteAddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GetRemoteAddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host_name = 1;</code>
   */
  java.lang.String getHostName();
  /**
   * <code>string host_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  boolean hasChannel();
  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  org.tensorflow.contrib.verbs.Channel getChannel();
  /**
   * <code>.tensorflow.Channel channel = 2;</code>
   */
  org.tensorflow.contrib.verbs.ChannelOrBuilder getChannelOrBuilder();

  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  java.util.List<org.tensorflow.contrib.verbs.MemoryRegion> 
      getMrList();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  org.tensorflow.contrib.verbs.MemoryRegion getMr(int index);
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  int getMrCount();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  java.util.List<? extends org.tensorflow.contrib.verbs.MemoryRegionOrBuilder> 
      getMrOrBuilderList();
  /**
   * <code>repeated .tensorflow.MemoryRegion mr = 3;</code>
   */
  org.tensorflow.contrib.verbs.MemoryRegionOrBuilder getMrOrBuilder(
      int index);
}
