// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/verbs/verbs_service.proto

package org.tensorflow.contrib.verbs;

public interface MemoryRegionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MemoryRegion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 remote_addr = 1;</code>
   */
  long getRemoteAddr();

  /**
   * <code>uint32 rkey = 2;</code>
   */
  int getRkey();
}
