// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/mpi_collectives/mpi_message.proto

package tensorflow.contrib.mpi_collectives;

public final class MpiMessage {
  private MpiMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MPIRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.contrib.mpi_collectives.MPIRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The request rank is necessary to create a consistent ordering of results,
     * for example in the allgather where the order of outputs should be sorted
     * by rank.
     * </pre>
     *
     * <code>int32 request_rank = 1;</code>
     */
    int getRequestRank();

    /**
     * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
     */
    int getRequestTypeValue();
    /**
     * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
     */
    tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType getRequestType();

    /**
     * <code>.tensorflow.DataType tensor_type = 3;</code>
     */
    int getTensorTypeValue();
    /**
     * <code>.tensorflow.DataType tensor_type = 3;</code>
     */
    org.tensorflow.framework.DataType getTensorType();

    /**
     * <code>string tensor_name = 4;</code>
     */
    java.lang.String getTensorName();
    /**
     * <code>string tensor_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getTensorNameBytes();

    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    boolean hasTensorShape();
    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    org.tensorflow.framework.TensorShapeProto getTensorShape();
    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    org.tensorflow.framework.TensorShapeProtoOrBuilder getTensorShapeOrBuilder();
  }
  /**
   * <pre>
   * An MPIRequest is a message sent from a rank greater than zero to the
   * coordinator (rank zero), informing the coordinator of an operation that
   * the rank wants to do and the tensor that it wants to apply the operation to.
   * </pre>
   *
   * Protobuf type {@code tensorflow.contrib.mpi_collectives.MPIRequest}
   */
  public  static final class MPIRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.contrib.mpi_collectives.MPIRequest)
      MPIRequestOrBuilder {
    // Use MPIRequest.newBuilder() to construct.
    private MPIRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPIRequest() {
      requestRank_ = 0;
      requestType_ = 0;
      tensorType_ = 0;
      tensorName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MPIRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestRank_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              tensorType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              tensorName_ = s;
              break;
            }
            case 42: {
              org.tensorflow.framework.TensorShapeProto.Builder subBuilder = null;
              if (tensorShape_ != null) {
                subBuilder = tensorShape_.toBuilder();
              }
              tensorShape_ = input.readMessage(org.tensorflow.framework.TensorShapeProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tensorShape_);
                tensorShape_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.class, tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code tensorflow.contrib.mpi_collectives.MPIRequest.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALLREDUCE = 0;</code>
       */
      ALLREDUCE(0),
      /**
       * <code>ALLGATHER = 1;</code>
       */
      ALLGATHER(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALLREDUCE = 0;</code>
       */
      public static final int ALLREDUCE_VALUE = 0;
      /**
       * <code>ALLGATHER = 1;</code>
       */
      public static final int ALLGATHER_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return ALLREDUCE;
          case 1: return ALLGATHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tensorflow.contrib.mpi_collectives.MPIRequest.RequestType)
    }

    public static final int REQUEST_RANK_FIELD_NUMBER = 1;
    private int requestRank_;
    /**
     * <pre>
     * The request rank is necessary to create a consistent ordering of results,
     * for example in the allgather where the order of outputs should be sorted
     * by rank.
     * </pre>
     *
     * <code>int32 request_rank = 1;</code>
     */
    public int getRequestRank() {
      return requestRank_;
    }

    public static final int REQUEST_TYPE_FIELD_NUMBER = 2;
    private int requestType_;
    /**
     * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
     */
    public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType getRequestType() {
      tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType result = tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.valueOf(requestType_);
      return result == null ? tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.UNRECOGNIZED : result;
    }

    public static final int TENSOR_TYPE_FIELD_NUMBER = 3;
    private int tensorType_;
    /**
     * <code>.tensorflow.DataType tensor_type = 3;</code>
     */
    public int getTensorTypeValue() {
      return tensorType_;
    }
    /**
     * <code>.tensorflow.DataType tensor_type = 3;</code>
     */
    public org.tensorflow.framework.DataType getTensorType() {
      org.tensorflow.framework.DataType result = org.tensorflow.framework.DataType.valueOf(tensorType_);
      return result == null ? org.tensorflow.framework.DataType.UNRECOGNIZED : result;
    }

    public static final int TENSOR_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object tensorName_;
    /**
     * <code>string tensor_name = 4;</code>
     */
    public java.lang.String getTensorName() {
      java.lang.Object ref = tensorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tensorName_ = s;
        return s;
      }
    }
    /**
     * <code>string tensor_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTensorNameBytes() {
      java.lang.Object ref = tensorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tensorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENSOR_SHAPE_FIELD_NUMBER = 5;
    private org.tensorflow.framework.TensorShapeProto tensorShape_;
    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    public boolean hasTensorShape() {
      return tensorShape_ != null;
    }
    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    public org.tensorflow.framework.TensorShapeProto getTensorShape() {
      return tensorShape_ == null ? org.tensorflow.framework.TensorShapeProto.getDefaultInstance() : tensorShape_;
    }
    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
     */
    public org.tensorflow.framework.TensorShapeProtoOrBuilder getTensorShapeOrBuilder() {
      return getTensorShape();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestRank_ != 0) {
        output.writeInt32(1, requestRank_);
      }
      if (requestType_ != tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.ALLREDUCE.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (tensorType_ != org.tensorflow.framework.DataType.DT_INVALID.getNumber()) {
        output.writeEnum(3, tensorType_);
      }
      if (!getTensorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tensorName_);
      }
      if (tensorShape_ != null) {
        output.writeMessage(5, getTensorShape());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestRank_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestRank_);
      }
      if (requestType_ != tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.ALLREDUCE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (tensorType_ != org.tensorflow.framework.DataType.DT_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, tensorType_);
      }
      if (!getTensorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tensorName_);
      }
      if (tensorShape_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTensorShape());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest)) {
        return super.equals(obj);
      }
      tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest other = (tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest) obj;

      boolean result = true;
      result = result && (getRequestRank()
          == other.getRequestRank());
      result = result && requestType_ == other.requestType_;
      result = result && tensorType_ == other.tensorType_;
      result = result && getTensorName()
          .equals(other.getTensorName());
      result = result && (hasTensorShape() == other.hasTensorShape());
      if (hasTensorShape()) {
        result = result && getTensorShape()
            .equals(other.getTensorShape());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_RANK_FIELD_NUMBER;
      hash = (53 * hash) + getRequestRank();
      hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + TENSOR_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + tensorType_;
      hash = (37 * hash) + TENSOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTensorName().hashCode();
      if (hasTensorShape()) {
        hash = (37 * hash) + TENSOR_SHAPE_FIELD_NUMBER;
        hash = (53 * hash) + getTensorShape().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An MPIRequest is a message sent from a rank greater than zero to the
     * coordinator (rank zero), informing the coordinator of an operation that
     * the rank wants to do and the tensor that it wants to apply the operation to.
     * </pre>
     *
     * Protobuf type {@code tensorflow.contrib.mpi_collectives.MPIRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.contrib.mpi_collectives.MPIRequest)
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.class, tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.Builder.class);
      }

      // Construct using tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestRank_ = 0;

        requestType_ = 0;

        tensorType_ = 0;

        tensorName_ = "";

        if (tensorShapeBuilder_ == null) {
          tensorShape_ = null;
        } else {
          tensorShape_ = null;
          tensorShapeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor;
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest getDefaultInstanceForType() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.getDefaultInstance();
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest build() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest buildPartial() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest result = new tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest(this);
        result.requestRank_ = requestRank_;
        result.requestType_ = requestType_;
        result.tensorType_ = tensorType_;
        result.tensorName_ = tensorName_;
        if (tensorShapeBuilder_ == null) {
          result.tensorShape_ = tensorShape_;
        } else {
          result.tensorShape_ = tensorShapeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest) {
          return mergeFrom((tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest other) {
        if (other == tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.getDefaultInstance()) return this;
        if (other.getRequestRank() != 0) {
          setRequestRank(other.getRequestRank());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (other.tensorType_ != 0) {
          setTensorTypeValue(other.getTensorTypeValue());
        }
        if (!other.getTensorName().isEmpty()) {
          tensorName_ = other.tensorName_;
          onChanged();
        }
        if (other.hasTensorShape()) {
          mergeTensorShape(other.getTensorShape());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int requestRank_ ;
      /**
       * <pre>
       * The request rank is necessary to create a consistent ordering of results,
       * for example in the allgather where the order of outputs should be sorted
       * by rank.
       * </pre>
       *
       * <code>int32 request_rank = 1;</code>
       */
      public int getRequestRank() {
        return requestRank_;
      }
      /**
       * <pre>
       * The request rank is necessary to create a consistent ordering of results,
       * for example in the allgather where the order of outputs should be sorted
       * by rank.
       * </pre>
       *
       * <code>int32 request_rank = 1;</code>
       */
      public Builder setRequestRank(int value) {
        
        requestRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The request rank is necessary to create a consistent ordering of results,
       * for example in the allgather where the order of outputs should be sorted
       * by rank.
       * </pre>
       *
       * <code>int32 request_rank = 1;</code>
       */
      public Builder clearRequestRank() {
        
        requestRank_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
       */
      public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
       */
      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType getRequestType() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType result = tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.valueOf(requestType_);
        return result == null ? tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
       */
      public Builder setRequestType(tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.contrib.mpi_collectives.MPIRequest.RequestType request_type = 2;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private int tensorType_ = 0;
      /**
       * <code>.tensorflow.DataType tensor_type = 3;</code>
       */
      public int getTensorTypeValue() {
        return tensorType_;
      }
      /**
       * <code>.tensorflow.DataType tensor_type = 3;</code>
       */
      public Builder setTensorTypeValue(int value) {
        tensorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.DataType tensor_type = 3;</code>
       */
      public org.tensorflow.framework.DataType getTensorType() {
        org.tensorflow.framework.DataType result = org.tensorflow.framework.DataType.valueOf(tensorType_);
        return result == null ? org.tensorflow.framework.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.tensorflow.DataType tensor_type = 3;</code>
       */
      public Builder setTensorType(org.tensorflow.framework.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tensorType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tensorflow.DataType tensor_type = 3;</code>
       */
      public Builder clearTensorType() {
        
        tensorType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tensorName_ = "";
      /**
       * <code>string tensor_name = 4;</code>
       */
      public java.lang.String getTensorName() {
        java.lang.Object ref = tensorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tensorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tensor_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTensorNameBytes() {
        java.lang.Object ref = tensorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tensorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tensor_name = 4;</code>
       */
      public Builder setTensorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tensorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tensor_name = 4;</code>
       */
      public Builder clearTensorName() {
        
        tensorName_ = getDefaultInstance().getTensorName();
        onChanged();
        return this;
      }
      /**
       * <code>string tensor_name = 4;</code>
       */
      public Builder setTensorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tensorName_ = value;
        onChanged();
        return this;
      }

      private org.tensorflow.framework.TensorShapeProto tensorShape_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tensorflow.framework.TensorShapeProto, org.tensorflow.framework.TensorShapeProto.Builder, org.tensorflow.framework.TensorShapeProtoOrBuilder> tensorShapeBuilder_;
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public boolean hasTensorShape() {
        return tensorShapeBuilder_ != null || tensorShape_ != null;
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public org.tensorflow.framework.TensorShapeProto getTensorShape() {
        if (tensorShapeBuilder_ == null) {
          return tensorShape_ == null ? org.tensorflow.framework.TensorShapeProto.getDefaultInstance() : tensorShape_;
        } else {
          return tensorShapeBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public Builder setTensorShape(org.tensorflow.framework.TensorShapeProto value) {
        if (tensorShapeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tensorShape_ = value;
          onChanged();
        } else {
          tensorShapeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public Builder setTensorShape(
          org.tensorflow.framework.TensorShapeProto.Builder builderForValue) {
        if (tensorShapeBuilder_ == null) {
          tensorShape_ = builderForValue.build();
          onChanged();
        } else {
          tensorShapeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public Builder mergeTensorShape(org.tensorflow.framework.TensorShapeProto value) {
        if (tensorShapeBuilder_ == null) {
          if (tensorShape_ != null) {
            tensorShape_ =
              org.tensorflow.framework.TensorShapeProto.newBuilder(tensorShape_).mergeFrom(value).buildPartial();
          } else {
            tensorShape_ = value;
          }
          onChanged();
        } else {
          tensorShapeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public Builder clearTensorShape() {
        if (tensorShapeBuilder_ == null) {
          tensorShape_ = null;
          onChanged();
        } else {
          tensorShape_ = null;
          tensorShapeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public org.tensorflow.framework.TensorShapeProto.Builder getTensorShapeBuilder() {
        
        onChanged();
        return getTensorShapeFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      public org.tensorflow.framework.TensorShapeProtoOrBuilder getTensorShapeOrBuilder() {
        if (tensorShapeBuilder_ != null) {
          return tensorShapeBuilder_.getMessageOrBuilder();
        } else {
          return tensorShape_ == null ?
              org.tensorflow.framework.TensorShapeProto.getDefaultInstance() : tensorShape_;
        }
      }
      /**
       * <code>.tensorflow.TensorShapeProto tensor_shape = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tensorflow.framework.TensorShapeProto, org.tensorflow.framework.TensorShapeProto.Builder, org.tensorflow.framework.TensorShapeProtoOrBuilder> 
          getTensorShapeFieldBuilder() {
        if (tensorShapeBuilder_ == null) {
          tensorShapeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.tensorflow.framework.TensorShapeProto, org.tensorflow.framework.TensorShapeProto.Builder, org.tensorflow.framework.TensorShapeProtoOrBuilder>(
                  getTensorShape(),
                  getParentForChildren(),
                  isClean());
          tensorShape_ = null;
        }
        return tensorShapeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.contrib.mpi_collectives.MPIRequest)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.contrib.mpi_collectives.MPIRequest)
    private static final tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest();
    }

    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPIRequest>
        PARSER = new com.google.protobuf.AbstractParser<MPIRequest>() {
      public MPIRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MPIRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPIRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPIRequest> getParserForType() {
      return PARSER;
    }

    public tensorflow.contrib.mpi_collectives.MpiMessage.MPIRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MPIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.contrib.mpi_collectives.MPIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Empty if the type is DONE or SHUTDOWN.
     * </pre>
     *
     * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
     */
    int getResponseTypeValue();
    /**
     * <pre>
     * Empty if the type is DONE or SHUTDOWN.
     * </pre>
     *
     * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
     */
    tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType getResponseType();

    /**
     * <code>string tensor_name = 2;</code>
     */
    java.lang.String getTensorName();
    /**
     * <code>string tensor_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getTensorNameBytes();

    /**
     * <pre>
     * Empty unless response_type is ERROR.
     * </pre>
     *
     * <code>string error_message = 3;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <pre>
     * Empty unless response_type is ERROR.
     * </pre>
     *
     * <code>string error_message = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * <pre>
   * An MPIResponse is a message sent from the coordinator (rank zero) to a rank
   * greater than zero, informing the rank of an operation should be performed
   * now. If the operation requested would result in an error (for example, due
   * to a type or shape mismatch), then the MPIResponse can contain an error and
   * an error message instead. Finally, an MPIResponse can be a DONE message (if
   * there are no more tensors to reduce on this tick of the background loop) or
   * SHUTDOWN if all MPI processes should shut down.
   * </pre>
   *
   * Protobuf type {@code tensorflow.contrib.mpi_collectives.MPIResponse}
   */
  public  static final class MPIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.contrib.mpi_collectives.MPIResponse)
      MPIResponseOrBuilder {
    // Use MPIResponse.newBuilder() to construct.
    private MPIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPIResponse() {
      responseType_ = 0;
      tensorName_ = "";
      errorMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MPIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              responseType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tensorName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.class, tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALLREDUCE = 0;</code>
       */
      ALLREDUCE(0),
      /**
       * <code>ALLGATHER = 1;</code>
       */
      ALLGATHER(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      /**
       * <code>DONE = 3;</code>
       */
      DONE(3),
      /**
       * <code>SHUTDOWN = 4;</code>
       */
      SHUTDOWN(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALLREDUCE = 0;</code>
       */
      public static final int ALLREDUCE_VALUE = 0;
      /**
       * <code>ALLGATHER = 1;</code>
       */
      public static final int ALLGATHER_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;
      /**
       * <code>DONE = 3;</code>
       */
      public static final int DONE_VALUE = 3;
      /**
       * <code>SHUTDOWN = 4;</code>
       */
      public static final int SHUTDOWN_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseType valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseType forNumber(int value) {
        switch (value) {
          case 0: return ALLREDUCE;
          case 1: return ALLGATHER;
          case 2: return ERROR;
          case 3: return DONE;
          case 4: return SHUTDOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType)
    }

    public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
    private int responseType_;
    /**
     * <pre>
     * Empty if the type is DONE or SHUTDOWN.
     * </pre>
     *
     * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
     */
    public int getResponseTypeValue() {
      return responseType_;
    }
    /**
     * <pre>
     * Empty if the type is DONE or SHUTDOWN.
     * </pre>
     *
     * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
     */
    public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType getResponseType() {
      tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType result = tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.valueOf(responseType_);
      return result == null ? tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.UNRECOGNIZED : result;
    }

    public static final int TENSOR_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tensorName_;
    /**
     * <code>string tensor_name = 2;</code>
     */
    public java.lang.String getTensorName() {
      java.lang.Object ref = tensorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tensorName_ = s;
        return s;
      }
    }
    /**
     * <code>string tensor_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTensorNameBytes() {
      java.lang.Object ref = tensorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tensorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMessage_;
    /**
     * <pre>
     * Empty unless response_type is ERROR.
     * </pre>
     *
     * <code>string error_message = 3;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Empty unless response_type is ERROR.
     * </pre>
     *
     * <code>string error_message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseType_ != tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.ALLREDUCE.getNumber()) {
        output.writeEnum(1, responseType_);
      }
      if (!getTensorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tensorName_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseType_ != tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.ALLREDUCE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseType_);
      }
      if (!getTensorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tensorName_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse)) {
        return super.equals(obj);
      }
      tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse other = (tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse) obj;

      boolean result = true;
      result = result && responseType_ == other.responseType_;
      result = result && getTensorName()
          .equals(other.getTensorName());
      result = result && getErrorMessage()
          .equals(other.getErrorMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + responseType_;
      hash = (37 * hash) + TENSOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTensorName().hashCode();
      hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An MPIResponse is a message sent from the coordinator (rank zero) to a rank
     * greater than zero, informing the rank of an operation should be performed
     * now. If the operation requested would result in an error (for example, due
     * to a type or shape mismatch), then the MPIResponse can contain an error and
     * an error message instead. Finally, an MPIResponse can be a DONE message (if
     * there are no more tensors to reduce on this tick of the background loop) or
     * SHUTDOWN if all MPI processes should shut down.
     * </pre>
     *
     * Protobuf type {@code tensorflow.contrib.mpi_collectives.MPIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.contrib.mpi_collectives.MPIResponse)
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.class, tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.Builder.class);
      }

      // Construct using tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseType_ = 0;

        tensorName_ = "";

        errorMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor;
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse getDefaultInstanceForType() {
        return tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.getDefaultInstance();
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse build() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse buildPartial() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse result = new tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse(this);
        result.responseType_ = responseType_;
        result.tensorName_ = tensorName_;
        result.errorMessage_ = errorMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse) {
          return mergeFrom((tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse other) {
        if (other == tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.getDefaultInstance()) return this;
        if (other.responseType_ != 0) {
          setResponseTypeValue(other.getResponseTypeValue());
        }
        if (!other.getTensorName().isEmpty()) {
          tensorName_ = other.tensorName_;
          onChanged();
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseType_ = 0;
      /**
       * <pre>
       * Empty if the type is DONE or SHUTDOWN.
       * </pre>
       *
       * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
       */
      public int getResponseTypeValue() {
        return responseType_;
      }
      /**
       * <pre>
       * Empty if the type is DONE or SHUTDOWN.
       * </pre>
       *
       * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
       */
      public Builder setResponseTypeValue(int value) {
        responseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empty if the type is DONE or SHUTDOWN.
       * </pre>
       *
       * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
       */
      public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType getResponseType() {
        tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType result = tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.valueOf(responseType_);
        return result == null ? tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Empty if the type is DONE or SHUTDOWN.
       * </pre>
       *
       * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
       */
      public Builder setResponseType(tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        responseType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empty if the type is DONE or SHUTDOWN.
       * </pre>
       *
       * <code>.tensorflow.contrib.mpi_collectives.MPIResponse.ResponseType response_type = 1;</code>
       */
      public Builder clearResponseType() {
        
        responseType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tensorName_ = "";
      /**
       * <code>string tensor_name = 2;</code>
       */
      public java.lang.String getTensorName() {
        java.lang.Object ref = tensorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tensorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tensor_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTensorNameBytes() {
        java.lang.Object ref = tensorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tensorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tensor_name = 2;</code>
       */
      public Builder setTensorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tensorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tensor_name = 2;</code>
       */
      public Builder clearTensorName() {
        
        tensorName_ = getDefaultInstance().getTensorName();
        onChanged();
        return this;
      }
      /**
       * <code>string tensor_name = 2;</code>
       */
      public Builder setTensorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tensorName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <pre>
       * Empty unless response_type is ERROR.
       * </pre>
       *
       * <code>string error_message = 3;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Empty unless response_type is ERROR.
       * </pre>
       *
       * <code>string error_message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Empty unless response_type is ERROR.
       * </pre>
       *
       * <code>string error_message = 3;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empty unless response_type is ERROR.
       * </pre>
       *
       * <code>string error_message = 3;</code>
       */
      public Builder clearErrorMessage() {
        
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empty unless response_type is ERROR.
       * </pre>
       *
       * <code>string error_message = 3;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.contrib.mpi_collectives.MPIResponse)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.contrib.mpi_collectives.MPIResponse)
    private static final tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse();
    }

    public static tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPIResponse>
        PARSER = new com.google.protobuf.AbstractParser<MPIResponse>() {
      public MPIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MPIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPIResponse> getParserForType() {
      return PARSER;
    }

    public tensorflow.contrib.mpi_collectives.MpiMessage.MPIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4tensorflow/contrib/mpi_collectives/mpi" +
      "_message.proto\022\"tensorflow.contrib.mpi_c" +
      "ollectives\032,tensorflow/core/framework/te" +
      "nsor_shape.proto\032%tensorflow/core/framew" +
      "ork/types.proto\"\225\002\n\nMPIRequest\022\024\n\014reques" +
      "t_rank\030\001 \001(\005\022P\n\014request_type\030\002 \001(\0162:.ten" +
      "sorflow.contrib.mpi_collectives.MPIReque" +
      "st.RequestType\022)\n\013tensor_type\030\003 \001(\0162\024.te" +
      "nsorflow.DataType\022\023\n\013tensor_name\030\004 \001(\t\0222" +
      "\n\014tensor_shape\030\005 \001(\0132\034.tensorflow.Tensor",
      "ShapeProto\"+\n\013RequestType\022\r\n\tALLREDUCE\020\000" +
      "\022\r\n\tALLGATHER\020\001\"\337\001\n\013MPIResponse\022S\n\rrespo" +
      "nse_type\030\001 \001(\0162<.tensorflow.contrib.mpi_" +
      "collectives.MPIResponse.ResponseType\022\023\n\013" +
      "tensor_name\030\002 \001(\t\022\025\n\rerror_message\030\003 \001(\t" +
      "\"O\n\014ResponseType\022\r\n\tALLREDUCE\020\000\022\r\n\tALLGA" +
      "THER\020\001\022\t\n\005ERROR\020\002\022\010\n\004DONE\020\003\022\014\n\010SHUTDOWN\020" +
      "\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_contrib_mpi_collectives_MPIRequest_descriptor,
        new java.lang.String[] { "RequestRank", "RequestType", "TensorType", "TensorName", "TensorShape", });
    internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_contrib_mpi_collectives_MPIResponse_descriptor,
        new java.lang.String[] { "ResponseType", "TensorName", "ErrorMessage", });
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
