// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/iterator.proto

package org.tensorflow.util;

public interface IteratorStateMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.IteratorStateMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A user-specified version string.
   * </pre>
   *
   * <code>string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * A user-specified version string.
   * </pre>
   *
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * Keys for tensors in the VariantTensorDataProto.
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <pre>
   * Keys for tensors in the VariantTensorDataProto.
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  int getKeysCount();
  /**
   * <pre>
   * Keys for tensors in the VariantTensorDataProto.
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <pre>
   * Keys for tensors in the VariantTensorDataProto.
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
