// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/event.proto

package org.tensorflow.util;

public interface SessionStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SessionStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.Event event = 1;</code>
   */
  java.util.List<org.tensorflow.util.Event> 
      getEventList();
  /**
   * <code>repeated .tensorflow.Event event = 1;</code>
   */
  org.tensorflow.util.Event getEvent(int index);
  /**
   * <code>repeated .tensorflow.Event event = 1;</code>
   */
  int getEventCount();
  /**
   * <code>repeated .tensorflow.Event event = 1;</code>
   */
  java.util.List<? extends org.tensorflow.util.EventOrBuilder> 
      getEventOrBuilderList();
  /**
   * <code>repeated .tensorflow.Event event = 1;</code>
   */
  org.tensorflow.util.EventOrBuilder getEventOrBuilder(
      int index);
}
